go: Tweak go-1-a
This updates the README to say 'function name' rather than 'signature'
when describing just the name of Description().

It also tweaks the stub file in two ways:

1. it edits the function comment to be a bit more go-ish (sorry), and
2. it renames the function parameter to `number` rather than `amount`,
since this is a countable, not a measurable.

Lastly, I updated the output from the test failures to make it a bit
more obvious what the 'got' vs the 'want' is (got and want are the
canonical terms used by the Go team, so I went with that).

    --- FAIL: TestTwelve (0.00s)
        go_1_a_test.go:40: Describe(12)
               got: "12"
              want: "1 dozen or 12".